### ISSUE TITLE
Dependabot security issues

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_kuet#42]
Please attend to this https://github.com/UNIMOODLE/moodle-mod_kuet/security/dependabot

Known security vulnerabilities detected

Dependency
semver	
Version
>= 7.0.0 < 7.5.2	
Upgrade to
~> 7.5.2
Defined in
package-lock.json
Vulnerabilities
CVE-2022-25883 Moderate severity
CVE-2022-25883 Moderate severity
Dependency
ip	
Version
= 2.0.0	
Upgrade to
~> 2.0.1
Defined in
package-lock.json
Vulnerabilities
CVE-2023-42282 Moderate severity
Dependency
tar	
Version
< 6.2.1	
Upgrade to
~> 6.2.1
Defined in
package-lock.json
Vulnerabilities
CVE-2024-28863 Moderate severity

**Comment by xpazv** [comment]
Is it correct to keep the **package.json** and **package-lock.json** as these are files related with the personal development context?

These are not Kuet dependencies, as it does not require npm modules to work. These are required for development, lik any other Moodle standard development.

**Comment by juacas** [comment]
IMHO, those files are needed for development of the module.
Then, can this security issues be safeky ignored?
Can this vulnerabilities compromise the integrity of development environments?
It's up to you to close this issue.

Regards

**Comment by xpazv** [comment]
The development enviroments are not usually public, therefore nothing should be compromised. As it happens with Moodle, It is recommended expose **package.json** file or run _npm i_ command of kuet in a public environment.

A development, preproduction or staging environment should not have this **package.json** file, since nothing will not be developed _"on top of them"_, it is used as a tool to develop, not as part of the code base. That is the reason why we cannot consider the use or the content of _package.json_ as vulnerability in itself.

The library reference contained in the file is only used to compile **css**, if nobody is going to write **css** on that environment, it is not necessary to have the **package.json** file neither run **npm install** command

**Comment by juacas** [comment]
Please check and triage new "High severity" depedabot vulnerablities.

**Comment by xpazv** [comment]
After reviewing it, it applies the same answer as below. The file package.json is not part of the code base, so we can consider the use or the content of the file as a vulnerability itself.
